server:
  port: 8003
spring:
  application:
    name: mocroServiceCloudProviderDept  #微服务名称，对外暴漏的微服务名称，十分重要
    #微服务名称，不做修改，与 micro-service-cloud-provider-dept-8001 的配置保持一致

##########spring cloud
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001:7001/eureka
  instance:
    instance-id: spring-cloud-provider-${server.port} #自定义服务名称信息
    prefer-ip-address: true #显示访问路径的 ip 地址

######## spring cloud 使用 Spring Boot actuator 监控完善信息
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: micro-service-cloud-provider-dept
  company.name: com.cloud.demo
  build.aetifactId: @project.artifactId@
  build.version: @project.version@