server:
  port: 8004
spring:
  application:
    name: microServiceCloudProviderDeptHystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance:
    instance-id: spring-cloud-provide-${server.port}
    # 自定义服务信息名称
    prefer-ip-address: true
    # 显示访问路径的ip

#########spring cloud 使用spring boot actuator 监控完善信息
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app.name: micro-service-cloud-provider-dept-hystrix
  company.name: com.cloud.mircoservicecloudproviderdepthystrix8004
  build.aetifactId: @project.artifactId@
  build.version: @project.version@