server:
  port: 8081
eureka:
  client:
    register-with-eureka: false #不像服务端注册服务
    fetch-registry: true #客户端去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
ribbon:
  ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
  ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间
  # 由于 OpenFeign 集成了 Ribbon ，其服务调用以及负载均衡在底层都是依靠 Ribbon
  #实现的，因此 OpenFeign 超时控制也是通过 Ribbon 来实现的。

#---- OpenFeign 日志增强
# Feign 为每一个 FeignClient 都提供了一个 feign.Logger 实例，通过它可以对 OpenFeign 服务绑定接口的调用情况进行监控。
logging:
  level:
  #feign 日志以什么样的级别监控该接口
    com.cloud.demo.service.DeptFeignService: debug
  #net.biancheng.c.service.DeptFeignService 是开启 @FeignClient 注解的接口（即服务绑定接口）的完整类名。也可以只配置部分路径，表示监控该路径下的所有服务绑定接口
  #debug：表示监听该接口的日志级别
