server:
  port: 8001
spring:
  application:
    name: mocroServiceCloudProviderDept
    # 微服务名称，对外暴漏的微服务名称 十分重要

    ### jdbc配置
#  datasource:
#    username:
#    password:
#    url:
#    driver-class-name: com.mysql.jdbc.Driver

######不检查spring.config.import=configserver:##################
#cloud.config.enabled:false

######################mybatis配置
# mybatis:
  #  mapper-locations:
  #  type-aliases-package:
    # configuration:
  #   map-underscore-to-camel-case: true # 驼峰命名法

##########spring cloud自定义服务名称和ip地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #   地址时7001注册中心 在application.yml 中暴漏出来的注册地址，集群版
  instance:
    instance-id: spring-cloud-provider-${server.port}
    # 自定义服务名称信息
    prefer-ip-address: true
    # 显示访问路径的ip

######## sppring cloud 使用spring boot actuator监控完善信息
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 在yml中* 属于关键字，所以需要家加引号
info:
  app.name: micro-service-cloud-provider-dept
  company.name: com.cloud.demo
  build.aetifactId: @project.artifactId@
  build.version: @project.version@