server:
  port: 8006
spring:
  application:
    name: mircoServiceCloudGateway
  cloud:
    gateway:
      routes:
      #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，
      #只给客户端暴露 API 网关的地址 8006
        - id: provider-dept-list-routh  #路由 id,没有固定规则，但唯一，建议与服务名对应
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://mocroServiceCloudProviderDept
          # #动态路由，使用服务名代替上面的具体带端口   http://eureka7001.com:9527/dept/list
          predicates:
          #以下是断言条件，必选全部符合条件
          #   - Path=/dept/list/** #断言，路径匹配 注意：Path 中 P 为大写
            - Path=/get/**  # 配和- PrefixPath=/dept 使用
            - Method=GET #只能时 GET 请求时，才能访问
          filters:  # 内置了31种gateway filter
           #   - AddRequestParameter=X-Request-Id,1024
             #过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 1024
            - PrefixPath=/dept
             #在请求路径前面加上 /dept
eureka:
  instance:
    instance-id: micro-service-cloud-gateway-8006
    hostname: mirco-service-cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
# 只有当外部（客户端）发送到 micro-service-cloud-gateway-9527 的 HTTP 请求同时满足以上所有的断言时，该请求才会被转发到指定的服务端中