server:
  port: 7003
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，职责就是维护服务的实例
    #并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/enreka/ # 单机版服务注册中心

      # 集群版 将当前的 Eureka Server 注册到 7003 和 7002 上，形成一组互相注册的 Eureka Server 集群
      defaultZone: http://eureka7001.com:7001/,http://eureka7002.com:7002/


